name: Driftwood CI
on: push

jobs:
  iOS_test: # job id
    name: An iOS demo test # job name
    runs-on: macos-latest  # operating system
    
    steps: # actions need to do.
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Pods Dependences
        run: | # A multi-line command use '|'
          pod repo update
          pod install
        working-directory: Demo/Driftwood_iOS # shell's working driectory
        shell: bash # use `bash` shell, which is default
      
      - name: CocoaPods Action
        uses: ty0x2333/cocoapods-action@master
        with:
          workspace: Demo/Driftwood_iOS/Driftwood_iOS.xcworkspace
          scheme: Driftwood_iOS
          additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'
          additional_lint_params: --private
