# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up latest Xcode
        # macos-latest always uses the latest stable Xcode, no need for explicit setup
        run: |
          echo "Using Xcode version:"
          xcodebuild -version

      - name: Set up latest Swift
        run: |
          echo "Swift version:"
          swift --version

      - name: Build and Test
        run: swift test
