# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Select latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4' # 指定最新的Xcode版本号


      - name: Set up latest Swift
        run: |
          echo "Swift version:"
          swift --version

      - name: Build and Test
        run: swift test
